### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by bbelderbos** [IshanMi/reverse-image-search-patent#3]
I would structure it as per recommendation: https://docs.python-guide.org/writing/structure/

So in your case:

```
$ tree -I venv
.
├── README.md
├── app.py
├── src
│   ├── patent_fetcher.py
│   ├── static
│   │   └── css
│   │       └── style.css
│   └── templates
│       ├── background.html
│       └── form.html
├── tests
└── user_queries.txt

5 directories, 7 files
```

If your project grows you can break out the scraping from the web code grouping those scripts into more folders / packages, but I am happy to have it all under `src/` for now.

**Comment by IshanMi** [comment]
I made the changes and read through the link, thanks Bob!

**Comment by bbelderbos** [comment]
ok awesome
